### ISSUE TITLE
player position X returning weird characters

### ISSUE THREAD

**Issue by 0xE666** [Nezzquikk/NWMM-New-World-MiniMap#1]
![XEqGTJMxSNnWMcN](https://user-images.githubusercontent.com/65376762/137355372-309ae8b8-dc99-48c3-a0fc-373c84e7b2ec.png)

im not sure how this would be fixed but could you give me your settings so i can try to adjust my game

**Comment by 0xE666** [comment]
also what version of tesseract do you have installed

**Comment by Nezzquikk** [comment]
My tesseract version is v5.0.0-alpha.20210811 from https://github.com/UB-Mannheim/tesseract/wiki

Tesseract shouldnt allow other characters beside [].,0123456789 i'd try updating to newest tesseract version.

**Comment by Nezzquikk** [comment]
Does your problem still occur?
