### ISSUE TITLE
Can not install requirements.txt

### ISSUE THREAD

**Issue by recentlyafish** [Nezzquikk/NWMM-New-World-MiniMap#2]
when I try installing requirements.txt:
```
C:\Users\USER\Documents\My Games\NewWorldMods\NWMM-New-World-MiniMap-0.8.1>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement pywin32==301 (from versions: 302)
ERROR: No matching distribution found for pywin32==301
```
running latest Python (3.10)

**Comment by 0xE666** [comment]
python --version (paste response)

also

pip install --upgrade pip then try again

**Comment by Nezzquikk** [comment]
Python 3.10 is currently NOT supported by pwin32 and thus it's not working for you.
Please downgrade to a lower Python version, i recommend Python 3.8.8 as it's stable with pywin32.
This should solve your problem.
